# Generated by Django 5.2.16 on 2026-07-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetection',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cropdetection',
            name='disease_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cropdetection',
            name='severity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
