# Generated by Django 5.2.16 on 2026-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_cropdetection_confidence_cropdetection_disease_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetection',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high')], max_length=50),
        ),
    ]
