# Generated by Django 5.2.16 on 2026-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_alter_cropdetection_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdetection',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
